import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Bonanzbar Bar Inventur",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="de">
      <body>
        <div className="flex flex-col h-screen justify-between">
        <header className="sticky top-0 row-start-1 flex gap-[24px] flex-wrap items-center justify-center bg-red-700 text-white p-4">
          <h1 className="text-2xl font-bold">Bonanzbar Bar Inventur</h1>
        </header>
        <main className="mb-auto min-h-screen p-12 flex flex-col items-center gap-16 bg-gray-400">
          {children}
        </main>
        <footer className="row-start-3 flex gap-[24px] flex-wrap items-center justify-center">
          @Bonanzbar 2025
        </footer>
        </div>
      </body>
    </html>
  );
}
